from PIL import Image
image = Image.open("assets/photos/hichem/p-1.png")
new_image = image.resize((80, 80))
new_image.save('image_400.jpg')
a= Image.open("assets/photos/kheira/p-0.png")
new_a = a.resize((80, 80))
new_a.save('monstre1.jpg')
b= Image.open("assets/photos/christophe/p-0.png")
new_b = b.resize((80, 80))
new_b.save('monstre2.jpg')
c= Image.open("assets/photos/darshaaaaan/p-0.png")
new_c = c.resize((80, 80))
new_c.save('monstre3.jpg')
d= Image.open("assets/photos/romaric/p-29.png")
new_d = d.resize((80, 80))
new_d.save('monstre4.jpg')